Refactor: change the last open statement to context manager
mittsh/db-s3-backup pull request #11
Opened 2017-01-24 13:46 UTC by divyenduz

2017-01-24 15:31 UTC, mittsh requested changes
Taking the chance to replace the general `Exception` by specific ones.

2017-01-24 15:31 UTC, mittsh commented on db_s3_backup.py
> +			except Exception, e:
Can you change this to `ValueError`? It's the right error for JSON parsing error.

2017-01-24 15:31 UTC, mittsh commented on db_s3_backup.py
>  	except Exception, e:
Can be changed to `IOError`

2017-01-24 15:31 UTC, mittsh commented
Thanks @divyenduz ! Ideally we could take this as a change to fine tune the exception handling…

2017-01-25 06:19 UTC, divyenduz commented
@mittsh Yes, that will make the code better. The changes have been made :)

2017-01-25 11:29 UTC, mittsh approved these changes

2017-01-25 11:29 UTC, mittsh commented
Thanks @divyenduz looks great

2017-01-25 11:29 UTC, merged